#! /usr/bin/env bash
: <<=cut
=pod

=head1  NAME

rp_utils - Utilities to update the researher profiles

=head1 SYNOPSIS

rp_utils --configuration=<configuration> <command> <args>

where <command> is one of: drop

rp_utils is a script the performs some commands on an active configuration of
the research profiles. L</"COMMANDS"> is summary of the commands that are
available.

=head1 GLOBAL OPTIONS

=over 4

=item B<--configuration=<configuration>>

This is the particular configuation that you want to act on.

=back

=cut

function init() {
    local opts=`$GETOPT -o c:hv --long verbose,help,configuration: -n 'rp_utils' -- "$@"`
    if [ $? != 0 ] ; then echo "Bad Command Options." >&2 ; exit 1 ; fi

    eval set -- "$opts"

    while true; do
	    case $1 in
	      -c | --configuration) G[configuration]=$2;  shift 2;;
	      -v | --verbose) G[verbose]=1;  shift ;;
        -h | --help ) exec pod2text $0;;
	      -- ) shift; break;;
	      *) shift; break;
      esac
    done

}

: <<='cut'

=pod

=head1 COMMANDS

The current commands are: delete

=cut

function main.cmd () {
    cmd=$1
    shift;
    case $cmd in
	    drop ) # API requests
	      $cmd "$@";
	      ;;
	    *)
	      exec pod2usage $0
	  ;;
    esac
}

function log() {
  [[ -n ${G[verbose]} ]] && (>&2 echo LOG: $@)
}

function err() {
  local n=1;
  if [[ $1 = '--quiet' ]] ; then
    n=$2;
  else
    n=$1
    shift
    (>&2 echo err: $@)
  fi
  exit $n;
}

=head1 DEPENDANCIES

rs_utils uses a number of external bash commands. These must be installed for
the elements script to work. These commands include httpie, xmlstarlet, and

=over 4

=item L<docker-compose|https://docs.docker.com/compose/>

All research-profile configurations are run through docker-compose
configurations. These configuations are what are used to

=item L<getopt>

Some applications do not use ${FLAGS_GETOPT_CMD:-getopt}

=back

=head1 AUTHOR

Quinn Hart <qjhart@ucdavis.edu>

=cut

#MAIN

# global Variables
declare -g -A G=(
  [noop]=''
  [http_ssl]="tls1.2"
  [http_print]="b"
  [http_session]="elements"
  [base]="/home/quinn/research-profiles/configurations"
  [util_docker_compose]="docker-compose"
);

OPTS=();
while true; do
	case $1 in
	  -*) OPTS+=($1); shift ;;
	  -- ) shift; break;;
	  *) break;
	esac
done

# Allow getopt to be somewhere else
GETOPT=${FLAGS_GETOPT_CMD:-getopt}

init "${OPTS[@]}"

[[ -n ${G[configuration]} ]] || { >&2 echo -e "No --configuration parameter specified\n"; exec pod2usage -exit 1 $0; }

main.cmd "$@"

exit 0;
